name: CD Fake
on:
  workflow_dispatch:
jobs:
  fake-staging-deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Fake Deploy to the environment
        run: echo "Deployment to the environment ${{ vars.DEPLOY_ENV }} is successful!"

  fake-test:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    needs: fake-staging-deploy
    steps:
      - name: Fake Test in the environment
        run: echo "Testing in the environment ${{ vars.DEPLOY_ENV }} is successful!"

  fake-production-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    needs: fake-test
    steps:
      - name: Fake Deploy to the environment
        run: echo "Deployment to the environment ${{ vars.DEPLOY_ENV }} is successful!"