name: CD Fake
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        options:
          - production
          - staging
jobs:
  fake-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Fake Deploy to the environment
        run: echo "Deployment to the environment ${{ vars.DEPLOY_ENV }} is successful!"